version: "3"

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    networks:
      - wordpress
    expose:
      - 3306
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD}
      - ROOT_PASSWORD=${ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    networks:
      - wordpress
    depends_on:
      - mariadb
    expose:
      - 9000
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - ROOT_PASSWORD=${ROOT_PASSWORD}
      - WP_USER=${WP_USER}
      - WP_PW=${WP_PW}
      - WP_EMAIL=${WP_EMAIL}
      - WP_USER_2=${WP_USER_2}
      - WP_EMAIL_2=${WP_EMAIL_2}
      - WP_PASSWORD_2=${WP_PASSWORD_2}
    volumes:
      - wordpress_data:/var/www/html/wordpress
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    networks:
      - wordpress
    depends_on:
      - wordpress
    ports:
      - 443:443
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html/wordpress
    restart: always

networks:
  wordpress:
    driver: bridge

volumes :
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/nel-brig/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/nel-brig/data/wordpress
    