version: "3"

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    networks:
      - wordpress
    ports:
      - 3306:3306
    env_file:
      - .env
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mariadb:/var/lib/mysql/
    # restart: always
    # init: true
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    networks:
      - wordpress
    depends_on:
      - mariadb
    ports:
      - 9000:9000
    env_file:
      - .env
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD}
    volumes:
      - wordpress:/var/www/html/wordpress
    # restart: always
    # init: true
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    networks:
      - wordpress
    depends_on:
      - wordpress
    ports:
      - 443:443
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_USER_PASSWOR=${MYSQL_USER_PASSWORD}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
    volumes:
      - wordpress:/var/www/html/wordpress
    # restart: always
    # init: true
      
networks:
  wordpress:
    driver: bridge

volumes :
  mariadb:
  wordpress: